services:
  postgres:
    image: postgres:16
    container_name: english-learning-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-english_learning}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: english-learning-adminer
    restart: unless-stopped
    ports:
      - "64549:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
      
  nuxt-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: english-learning-nuxt
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/english_learning
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
    name: english_learning_pg_data 